print("STUDENT'S BIO DATA")
a = input("First Name:")
b = input("Last Name:")
c = input("Middle Name:")
d = input("Name of School:")
e = input("Name of Faculty:")
f = input("Life Goal:")
print("Hi" + (a,b,c))
print("welcome")
print("how are you")
